### ISSUE TITLE
Create and add title

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#1]
Try to find a good title for a game and design it

**Comment by alkaitagi** [comment]
New title is **Sungazer**

**Comment by Muniriy** [comment]
Ok, now the game should begin with this title in starting window

**Comment by alkaitagi** [comment]
Loading screen 
![image](https://user-images.githubusercontent.com/32439229/60108007-94cb6600-9770-11e9-86bc-de81b14085da.png)

**Comment by Muniriy** [comment]
I advise thinking more on the logo. For now, it does not look very good.

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/60520284-cb176100-9ced-11e9-8d69-9827549aa437.png)
![image](https://user-images.githubusercontent.com/32439229/60520291-ceaae800-9ced-11e9-90ac-c625dedb9182.png)

**Comment by Muniriy** [comment]
Update logo on web

**Comment by alkaitagi** [comment]
Done
![image](https://user-images.githubusercontent.com/32439229/60575592-825eb700-9d84-11e9-8689-244951fe275c.png)
