### ISSUE TITLE
Add respawn animation

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#10]
After the death camera should move to the centre of a region to show a player where he died. It can be helpful in cases of necessity to find keys. After the death with all collected keys, the player should be moving towards the Sun

**Comment by Muniriy** [comment]
Add 3 seconds after respawn during which player cannot die using shield

**Comment by alkaitagi** [comment]
Added
![image](https://user-images.githubusercontent.com/32439229/60515956-622beb00-9ce5-11e9-9302-4c378ec4e78a.png)
