### ISSUE TITLE
Decrease the circle for the main region

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#11]
Too much space inside the main circle with 3 gates. It can be decreased to save time for testers and us

**Comment by alkaitagi** [comment]
I put Gates further from Sun since we needed more space for "completion" effects. Now the center does not seem to be such desert.

**Comment by Muniriy** [comment]
Ok, I'll check it after releasing new version

**Comment by Muniriy** [comment]
Looks good
