### ISSUE TITLE
Check the browser of a player

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#13]
If the browser of a player is not compatible, then the game should not start. Recommendation to use another browser should be given https://docs.unity3d.com/Manual/webgl-browsercompatibility.html

**Comment by Muniriy** [comment]
Add sentence "Please use Google Chrome... or Mozilla Firefox..."

**Comment by alkaitagi** [comment]
Alert:
`if (!document.createElement('canvas').getContext('webgl2'))
            alert("This browser does not support WebGL2! Please, use the latest Mozilla Firefox or Google Chrome.");`

**Comment by Muniriy** [comment]
...on Desktop

**Comment by alkaitagi** [comment]
"This browser is not supported! Please, use the latest Mozilla Firefox or Google Chrome on desktop."

**Comment by alkaitagi** [comment]
"This browser is not supported! Please, use the latest Mozilla Firefox or Google Chrome on desktop."
