### ISSUE TITLE
Check the OS of a player

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#14]
Deny playtesting in case of any mobile OS. Use only Windows, macOS and Linux.

**Comment by alkaitagi** [comment]
Achieved with this code:
`if (
            navigator.userAgent.match(/Android/i)
            || navigator.userAgent.match(/webOS/i)
            || navigator.userAgent.match(/iPhone/i)
            || navigator.userAgent.match(/iPad/i)
            || navigator.userAgent.match(/iPod/i)
            || navigator.userAgent.match(/BlackBerry/i)
            || navigator.userAgent.match(/Windows Phone/i)
        )
            alert("Mobile devices are not supported! Please, run on desktop.");`

**Comment by Muniriy** [comment]
Combine phrases about OS and browser.

**Comment by alkaitagi** [comment]
"This browser is not supported! Please, use the latest Mozilla Firefox or Google Chrome on desktop."

**Comment by alkaitagi** [comment]
"This browser is not supported! Please, use the latest Mozilla Firefox or Google Chrome on desktop."
