### ISSUE TITLE
Add developer version box in left top part

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#2]
- [x] Add developer's menu with "Restart the game", "Skip the region", ...
- [x] Use backquote for showing and hiding the developer's information
- [x] For FPS add "FPS" word
- [x] Add countdowns for regions
- [x] Add number of death in the current region
- [x] Add to developer's menu "Skip the pole"

**Comment by alkaitagi** [comment]
Work in progress
![image](https://user-images.githubusercontent.com/32439229/60089351-f5df4380-9748-11e9-8bbb-51423085a8fe.png)

**Comment by Muniriy** [comment]
One click - opened, next click - closed

**Comment by alkaitagi** [comment]
As `esc` is used for exiting fullscreen mode in browsers, `ctrl+~` is used instead for toggling developer panel. Also game restart is easier achieved through usual web page reload.
