### ISSUE TITLE
Missing explanation of buttons

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#29]
No explanation about which buttons should be pressed to move, jump, turn on the torch, pause, etc. After a long time of not playing the game, I had issues with it. Please add it to tutorial

**Comment by alkaitagi** [comment]
Added initial-tutorial controls explanation, as well as a per-module note for every region tutorial.
![image](https://user-images.githubusercontent.com/32439229/86040908-7f58de00-ba4d-11ea-983a-5225beb76a32.png)
