### ISSUE TITLE
Time limit ending bug

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#32]
When the time has ended in the region, colours of all objects have changed and post-survey has begun without notification. Notification should be shown after crossing the time limit

**Comment by alkaitagi** [comment]
Added a note about the time limit on the initial tutorial.
![image](https://user-images.githubusercontent.com/32439229/86040189-40765880-ba4c-11ea-90a7-4f2e9ad79a9e.png)

**Comment by alkaitagi** [comment]
Added an on-screen message when player is being withdrawn.
![image](https://user-images.githubusercontent.com/32439229/86040378-9a771e00-ba4c-11ea-90aa-c85ba2327bae.png)
