### ISSUE TITLE
Add final scene with acknowledgements

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#4]
After all three regions, the player has to get relief and understand that he/she has successfully finished the game. Music in the final place can be even WAV, the mood of it should also be positive. The text of acknowledgements should include all the people, which took part in this project and AIGD lab

**Comment by Muniriy** [comment]
Make fonts more visible

**Comment by alkaitagi** [comment]
Fixed
![image](https://user-images.githubusercontent.com/32439229/60515788-0f523380-9ce5-11e9-803d-8ec411051d14.png)

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/60520332-dd919a80-9ced-11e9-8e39-b2854db3a2aa.png)
