### ISSUE TITLE
Add tutorial tips

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#5]
During the flight to regions, tips have to be added:
1. Nebula (You found a torch, use it to avoid asteroids; You have to find all 10 keys to save the Sun...)
2. Worm-hole (maybe region should be renamed because of changing the concept) (Avoid comets, they can destroy your spaceship; Beware of asteroids, they will try to push you away; You have to find all 10 keys to save the Sun...)
3. Attack (Avoid collisions with enemy spaceships, they are kamikaze! Terminate all of them and collect all 10 keys to save the Sun...)

**Comment by alkaitagi** [comment]
I propose renaming Wormhole into Orbits, and Attack to Invasion.

**Comment by Muniriy** [comment]
Accepted

**Comment by Muniriy** [comment]
Add screenshots of described things

**Comment by Muniriy** [comment]
Add scrolling inside tutorials. Each tip should be provided with screenshoot

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/62318230-0a2f0280-b4a4-11e9-968e-5fe9f4794b7e.png)
![image](https://user-images.githubusercontent.com/32439229/62318309-3ba7ce00-b4a4-11e9-960e-20425b412c2a.png)
![image](https://user-images.githubusercontent.com/32439229/62318360-57ab6f80-b4a4-11e9-99c4-31fce88285f9.png)

**Comment by alkaitagi** [comment]
For each region general info, the enemy and the ship module information is being displayed.

**Comment by Muniriy** [comment]
- [x] Increase the font for the region name
- [x] Add more space between tips
- [x] Add words "Active Module:" before the module
- [x] Add words "Enemy:" before the name of enemy
- [x] For the Orbits region add information about asteroids
- [x] Delete all dots and commas in the end of sentences
- [x] Add tutorial tips before the game about 3 regions

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/63020182-13f23600-bea6-11e9-8dbe-da1b3d7e8bb0.png)
