### ISSUE TITLE
Add pole before the game

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#6]
Questions:
1. What is your name? (Field for letters, max 20 digits)
2. What is your surname? (Field for letters, max 20 digits)
3. What is your gender? (Male, Female, Non-binary)
4. What is your age? (Field for numbers, max 3 digits)
5. What is your citizenship? (Field for letters, max 20 digits)
6. What is your current status? (University student, College student, School student, PhD-student, Professor/Teacher, Employer, Unemployed, Other (Field for symbols, max 20 digits))
7. How much do you agree with this statement: "I enjoy Indie Games?" (Strongly agree, Agree, Slightly agree, No opinion, Somewhat disagree, Disagree, Strongly Disagree)
8. How much do you agree with this statement: "I enjoy Adventure Games?" (Strongly agree, Agree, Slightly agree, No opinion, Somewhat disagree, Disagree, Strongly Disagree) 
9. Do you have experience of playing Adventure games (e.g. examples)? (Yes, No, Not sure)
10. How many hours per week do you play Adventure games? (Do not play; Less than 1 hour; 1-5 hours; 5-10 hours; 10-20 hours; More than 20 hours)

**Comment by Muniriy** [comment]
Fix: 
- [x] Improve scrolling
- [x] Add Tab for button for changing focus
- [x] Answer to question 3, 6, 7, 8, 10 and for other poles has to be initially PLEASE CHOOSE or something like this
- [x] Find answers for question 10
- [x] Make questions mandatory for answering
- [x] Minimal length for Name, Surname should be 2, for the age maximum length is 2
- [x] Change the structure of question about citizenship to a dropdown list
- [x] Q7, Q8 change second word of last option to "disagree"
- [x] Q6 option Other should provide a field with minimal length 3 and maximal length 50

**Comment by alkaitagi** [comment]
UI elements focus can be controller trough arrows

**Comment by alkaitagi** [comment]
Added invalid answers highlighting.
![image](https://user-images.githubusercontent.com/32439229/60548229-3d0d9b80-9d2a-11e9-9b09-f82b23f393af.png)

**Comment by alkaitagi** [comment]
Addressed all the issues to be fixed

**Comment by alkaitagi** [comment]
Regarding question 6:
![image](https://user-images.githubusercontent.com/32439229/62388675-9a358080-b566-11e9-852d-9f34c02b224c.png)

**Comment by alkaitagi** [comment]
Improved the pole with tab-key navigation and fast country input.

**Comment by Muniriy** [comment]
Q9 does not have predefined answers Yes/No/Not sure

**Comment by alkaitagi** [comment]
Fixed
![image](https://user-images.githubusercontent.com/32439229/107141079-84610280-6937-11eb-8ab8-5b438ee4bf7f.png)
