### ISSUE TITLE
Add pole after each region

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#7]
Questions:
1. Which emotions did you feel while playing? (Joy, Surprise, Anticipation, Fear, Anger, Sadness, Disgust, Trust, Indifference, Others (Field for 50 symbols, at least 4 symbols))
2. Did the music improve your playing experience? (Improved significantly, Improved slightly, Didn't notice, Worsened slightly, Worsened significantly)
3. Was the music adapting to your gameplay? (Strongly agree, Agree, Slightly agree, No opinion, Somewhat disagree, Disagree, Strongly disagree)
4. In case of answer Strongly agree, Agree, Slightly agree to the third question the fourth question should appear -> Which game action/moment affected the soundtrack? What was changed in the soundtrack and how? (Field for 200 symbols, at least 10 symbols)

**Comment by Muniriy** [comment]
"Other" text field should contain only English letters and symbols without numbers

**Comment by alkaitagi** [comment]
Added `InputField` component with required functionality.

**Comment by Muniriy** [comment]
Other text field should be controlled by Other button

**Comment by alkaitagi** [comment]
Inactive state:
![image](https://user-images.githubusercontent.com/32439229/63021605-9e886480-bea9-11e9-959d-2091e42241e2.png)
