### ISSUE TITLE
Add final pole after all regions

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#8]
Do you know what is ... in music theory? (Yes, I have advanced knowledge about it; Yes, I feel confident about it; Not sure; Almost do not know anything; No, I do not know)

This pole should appear after the third region main pole

**Comment by Muniriy** [comment]
Separate from other questions

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/60528251-b2627780-9cfc-11e9-982a-02426dd6cb0b.png)

**Comment by Muniriy** [comment]
Add header above the final question and delete numeration for it

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/60576193-a1aa1400-9d85-11e9-976c-743a765d69f5.png)

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/60576281-c7cfb400-9d85-11e9-9a5b-b81759642725.png)

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/60576417-082f3200-9d86-11e9-9df4-cfeaef504b96.png)
