### ISSUE TITLE
Statistics collection

### ISSUE THREAD

**Issue by Muniriy** [alkaitagi/SpaceSound#9]
Add a mechanism to export all data about game progress and region pole after passing through each region. Initially, statistics should contain
1. Tester ID
2. Region name
3. Game configuration ID (game and music factor correlation). (Leave empty for now)
4. Music ID (Leave empty for now)
5. The number of deaths 
6. The time of deaths
7. The number of collected keys
8. The time of collecting keys. 
9. The time of finalizing the region

In future collected data will contain more things. Tester ID should be unique for each tester

**Comment by alkaitagi** [comment]
The reason for deaths seems irrelevant since there is only single death source on every region.

**Comment by Muniriy** [comment]
Accepted

**Comment by Muniriy** [comment]
In the field of Statistics test focus changes by pressing any key

**Comment by alkaitagi** [comment]
Made the text field read-only
